#ifndef COMPONENTES_H
#define COMPONENTES_H

// Definições do display OLED
#define OLED_I2C_ADDRESS 0x3C
#define OLED_CONTROL_BYTE_CMD_STREAM 0x00
#define OLED_CONTROL_BYTE_DATA_STREAM 0x40

// Comandos do display
#define OLED_CMD_SET_CHARGE_PUMP 0x8D
#define OLED_CMD_SET_SEGMENT_REMAP 0xA1
#define OLED_CMD_SET_COM_SCAN_MODE 0xC8
#define OLED_CMD_DISPLAY_ON 0xAF
#define OLED_CMD_SET_MEMORY_ADDR_MODE 0x20
#define OLED_CMD_SET_COLUMN_RANGE 0x21
#define OLED_CMD_SET_PAGE_RANGE 0x22

// Definições de pinos
#define SDA_PIN GPIO_NUM_19
#define SCL_PIN GPIO_NUM_18

// Botões de navegação
#define SELECT_BUTTON GPIO_NUM_14
#define NAVIGATE_BUTTON GPIO_NUM_4

// Configurações do display
#define WIDTH 128
#define HEIGHT 64
#define BUFFER_SIZE (WIDTH * HEIGHT / 8)

// MPU-6050
#define MPU6050_ADDR 0x68
#define MPU6050_ACCEL_XOUT_H 0x3B
#define MPU6050_PWR_MGMT_1 0x6B

// BUZZER
#define BUZZER_PIN GPIO_NUM_25
#define BUZZER_LEDC_CHANNEL LEDC_CHANNEL_0
#define BUZZER_LEDC_TIMER LEDC_TIMER_0
#define BUZZER_LEDC_MODE LEDC_HIGH_SPEED_MODE
#define BUZZER_LEDC_DUTY_RES LEDC_TIMER_8_BIT


#endif
